"""add is_shared to vehicles

Revision ID: 42b26bf6d488
Revises: f1a2b3c4d5e6
Create Date: 2026-05-02 13:25:51.518378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42b26bf6d488'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charging_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_charging_sessions_tessie_charge_id'))

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_shared', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('is_shared')

    with op.batch_alter_table('charging_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_charging_sessions_tessie_charge_id'), ['tessie_charge_id'], unique=1)

    # ### end Alembic commands ###
