"""recompute maintenance next_due_odometer (fix miles-interval inflation)

Recomputes next_due_odometer for existing maintenance schedules that were
saved with the old, buggy calculation (issue #230), where a km-converted
interval was added to an odometer value already stored in the user's native
unit. The fix is model-driven: it simply re-runs MaintenanceSchedule
.calculate_next_due() for every schedule that has a last_performed_odometer,
so the stored value is regenerated by the corrected code path. No column
lists are hardcoded.

Revision ID: d4e5f6a7b8c9
Revises: c3d4e5f6a7b8
Create Date: 2026-07-14 00:00:00.000000

"""
from alembic import op
from sqlalchemy import inspect
from sqlalchemy.orm import Session

revision = 'd4e5f6a7b8c9'
down_revision = 'c3d4e5f6a7b8'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = inspect(bind)

    if 'maintenance_schedules' not in inspector.get_table_names():
        return

    # Import lazily so the migration only depends on the models when it runs.
    from app.models import MaintenanceSchedule

    session = Session(bind=bind)
    try:
        schedules = session.query(MaintenanceSchedule).filter(
            MaintenanceSchedule.last_performed_odometer.isnot(None)
        ).all()
        for schedule in schedules:
            # Only odometer-interval schedules had the bug; date-only ones are
            # untouched by calculate_next_due's odometer branch anyway.
            if schedule.interval_km or schedule.interval_miles:
                schedule.calculate_next_due()
        session.commit()
    except Exception:
        # A data recompute must never break the upgrade chain. If anything
        # goes wrong, leave stored values as-is; they will be corrected on the
        # schedule's next edit/completion via the fixed calculate_next_due().
        session.rollback()
    finally:
        session.close()


def downgrade():
    # Data-only recomputation; there is nothing to reverse.
    pass
